services:
  # service for redis add test
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass passwordRedis
    volumes:
      - redis:/data

  # service for MySQL
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    container_name: mysql_container
    env_file: ".env"
    ports:
      - 3306:3306
    # create mysql volume and mount to /var/lib/mysql
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
    environment:
      # MySQL root password
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      # MySQL database
      MYSQL_DATABASE: ${DB_NAME}

  # Laravel web application
  # Build via Dockerfile
  webapp:
    image: ndlrfz/laravelapp:latest
    restart: always
    container_name: webapp_container
    env_file: ".env"
    environment:
      - APPLICATION_DOMAIN=${DOMAIN}
      - CONTAINER_ROLE=webapp
    # Running when mysql is available
    depends_on:
      - mysql
      - redis
    # expose port 9000 - host:container
    ports:
      - 8002:9000
    # create volumes public and vendor
    # public mount to /var/www/html/public
    # vendor mount to /var/www/html/vendor
    volumes:
      - public:/var/www/html/public
      - vendor:/var/www/html/vendor

  scheduler:
    image:
      ndlrfz/laravelapp:latest
      #restart: always
    volumes:
      - storage-logs:/var/www/html/storage/logs
    environment:
      CONTAINER_ROLE: scheduler
    depends_on:
      - mysql
      - redis
    env_file: ".env"

  queue:
    image:
      ndlrfz/laravelapp:latest
      #restart: always
    volumes:
      - storage-logs:/var/www/html/storage/logs
    environment:
      CONTAINER_ROLE: queue
    depends_on:
      - mysql
      - redis
    env_file: ".env"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin_container
    # expose port 8000 for phpMyAdmin - host:container
    ports:
      - 8000:80
    # link to mysql service
    links:
      - mysql
    # environments for phpMyAdmin service
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    # volumes that upload files to container
    # ./docker/phpmyadmin/.htpasswd - passwd file for basic authentication
    # mount to /etc/apache/.htpasswd
    # ./docker/phpmyadmin/basic-auth.conf - enable Apache basic auth
    # mount to /etc/apache2/conf-enabled/basic-auth.conf
    volumes:
      - ./docker/phpmyadmin/.htpasswd:/etc/apache2/.htpasswd
      - ./docker/phpmyadmin/basic-auth.conf:/etc/apache2/conf-enabled/basic-auth.conf

# volumes with 'local' driver
volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"
  public:
    driver: "local"
  vendor:
    driver: "local"
  storage-logs:
    driver: "local"
