name: Deploy Application

on:
  push:
    branches: ["main"]

jobs:
  build:
    environment: mindo-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ndlrfz/laravelapp:latest,ndlrfz/laravelapp:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: curl
        uses: sozo-design/curl@v1.0.2
        with:
          args: --user jenkins:${{ secrets.JENKINS_PASSWORD }} https://cicd.ndlrfz.web.id/job/devops-test/build?token=${{ secrets.JENKINS_PASSWORD }}
